---
# ============================================================= PLAY =====================================================
# This playbook will create common resources in Azure
# Inputs:

  # the name of this playbook. You see this back in the default logging
- name: Azure Create Common Resources

  # There is no concepts of hosts in a public cloud. We use localhost to specify that this playbook runs from the
  # Ansible execution host (engine or tower).
  hosts: localhost
  
  # likewise, since we use the Azure API, there is no concept of a connection. Thus we specify local
  connection: local
  
  # this is a way to specify files that contain vars
  vars_files:
    # here we include a var file from a sub directory "files"
    files/azure_vars
  
   # We now start the tasks that must be executed in order
  tasks:
      
  # the retry logic of the following 3 tasks is that if this playbook is
  # run multiple times concurrently azure will try to create these objects
  # at exactly the same time because the present state is not there for all
  # of the instances. This produces errors. This is a common construct to prevent
  # mid-air collisions of these kinds.
  - name: create Azure resource group
    azure_rm_resourcegroup:
      name: '{{ project }}'
      location: westeurope
      state: present
   # register: arm_result
   # until: arm_result.failed != True
   # retries: 2
   # delay: 10
    
  - name: create Azure virtual network in resource group
    azure_rm_virtualnetwork:
      name: '{{ project }}'
      resource_group: '{{ project }}'
      address_prefixes_cidr:
      - 10.1.0.0/16
      state: present
   # register: arm_result
   # until: arm_result.failed != True
   # retries: 2
   # delay: 10
  
  - name: create Azure subnet in virtualnetwork
    azure_rm_subnet:
      name: '{{ project }}'
      state: present
      virtual_network_name: '{{ project }}'
      resource_group: '{{ project }}'
     address_prefix_cidr: 10.1.0.0/24
   # register: arm_result
   # until: arm_result.failed != True
   # retries: 2
   # delay: 10

- name: Create an availability set with default options
  azure_rm_availabilityset:
    name: "{{ project }}"
    location: eastus
    resource_group: "{{ project }}"
