---
# playbook to delete a single VM is part of users inventory.
# inputs:
# - vm_name: the name of the VM to delete.
- name: Azure Delete VM
  hosts: localhost
  connection: local
  vars_files:
    files/azure_vars
  vars:
    azure_vm_name: "{{ vm_name }}{{ tower_user_name[-2:] }}"

  tasks:
  # Delete VM from azure when vm_name is part of the array of vms just constructed
  - name: Delete Azure Virtual Machine
    azure_rm_virtualmachine:
      name: '{{ azure_vm_name }}'
      resource_group: 'AnsibleWorkshop'
      state: absent
