---
- name: "Clean Azure of all VM's of user {{ tower_user_name }}"
  hosts: localhost]
  connection: local
  gather_facts: no
  vars:
    group: "user_{{ tower_user_name }}"
    vms: "{{ groups[group] }}" 

  tasks:
  - name: "Delete Virtual Machines in Azure based on inventory of user {{ tower_user_name }}"
    azure_rm_virtualmachine:
      name: '{{ item }}'
      resource_group: 'AnsibleWorkshop'
      state: absent
    loop: "{{ vms }}"
    when confirm=="yes"
