---
- name: Azure Delete VM
  hosts: localhost
  connection: local
  vars_files:
    files/azure_vars
    
  tasks:
  - name: Delete Azure Virtual Machine
    azure_rm_virtualmachine:
      name: '{{ vm_name }}'
      resource_group: 'AnsibleWorkshop'
      state: absent
