# playbook to delete a single VM
# inputs:
# - vm_name: the name of the VM to delete. It is currently NOT checked against the current inventory

---
- name: Azure Delete VM
  hosts: localhost
  connection: local
  vars_files:
    files/azure_vars
    
  tasks:
  - name: Delete Azure Virtual Machine
    azure_rm_virtualmachine:
      name: '{{ vm_name }}'
      resource_group: 'AnsibleWorkshop'
      state: absent
    when vm_name in groups['user']
